# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'SteviaLayout'
  pod 'NVActivityIndicatorView'


  # Pods for iOS-challenge

  target 'iOS-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  
  end

  target 'iOS-challengeUITests' do
    # Pods for testing
  end

end
